<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form generator</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <?php
            use App\classes\FormBuilder;

            require 'vendor/autoload.php';

            $form = new FormBuilder;
            
            echo $form->open('index.php', 'POST');
        ?>
        <div class="mb-3 col-3">
            <?php
                echo $form->label('some-id', 'Some label');
                echo $form->input('text', 'Enter value', '');
            ?>
        </div>
        <div class="mb-3 col-3">
            <?php
                echo $form->input('password', 'Enter password', '');
            ?>
        </div>
        <div class="mb-3 col-4">
            <?php
                echo $form->password('Enter password');
                echo $form->textarea('Enter text');
                echo $form->submit();
                echo $form->close();
            ?>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>