<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form task</title>
</head>
<body>
    <div class="container">
        <h1>Registracija į kursus</h1>
        <hr>
        <form action="" method="POST">
            <p>Vardas: 
                <input type="text" name="name" value="<?php echo isset($msg['error']) && isset($_POST['name']) ? $_POST['name'] : ''; ?>")>
            </p>
            <p>Pavardė: 
                <input type="text" name="lastname" value="<?php echo isset($msg['error']) && isset($_POST['lastname']) ? $_POST['lastname'] : ''; ?>")>
            </p>
            <p>Miestas: 
                <select name="city">
                    <?php foreach ($cities as $city): ?>
                    <option value="<?php echo $city; ?>"><?php echo $city; ?></option>
                    <?php endforeach; ?>
                </select>
            </p>
            <div>
                <h3>Programavimo kalba:</h3>
                <?php foreach ($langs as $lang): ?>
                <p><?php echo $lang; ?><input type="checkbox" name="language[]" value="<?php echo $lang; ?>"></p>
                <?php endforeach; ?>    
            </div>
            <h4>Papildoma informacija</h4>
            <textarea name="info" cols="40" rows="5" placeholder="Pvz. Turite C++ programavimo patirties"></textarea>
            <p>
                <button type="submit">Siųsti</button>
            </p>
        </form>

        <?php if (count($msg)): ?>
                <?php if (isset($msg['error'])): ?>
                    <p><?= $msg['msg']; ?></p>
                <?php elseif (isset($msg['success'])): ?>
                    <p><?= $msg['msg']; ?></p>
                <?php endif; ?>
        <?php endif; ?>

    </div>
</body>
</html>